name: Actualizar Componentes
run-name: Push hecho por parte de ${{ github.actor }}

on: 
  push:
    branches:
      - develop
permissions:
      contents: write  
      pull-requests: write

jobs:
  actualizar-deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: Clonar repositorio
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.github_token }}
      - name: Conseguir los nombres de los .json
        id: lista-json
        run: |
          all_archivos=$(find . -maxdepth 1 -type f -name "*.json" -exec basename {} .json \;)
           
           echo "archivos<<EOF" >> $GITHUB_OUTPUT
           echo "$all_archivos" >> $GITHUB_OUTPUT
           echo "EOF" >> $GITHUB_OUTPUT
           
      - name: Actualizar los nuevos componentes
        run: |
          componentes="${{ steps.lista-json.outputs.archivos }}"
          options=$(echo "$componentes" | tr '\n' ' ' | sed 's/^/    - /')

          sed -i  "/component:/,/options:/ {
              /options:/ {  
                n
                s|.*|$options|
              }
          }" .github/workflows/Deploy.yml
      
      - name: Instalar GitHub CLI
        run: sudo apt install gh
        
      - name: Autenticarse con gh
        run: echo "${{ secrets.MY_TOKEN }}" | gh auth login --with-token
        
      - name: Crear rama y hacer push
        run: |
            
            git config --global user.email "hamzafuego2@gmail.com"
            git config --global user.name "${{github.actor}}"
            git checkout -b feature/mi-rama
            git add .
            git commit -m "Cambios automáticos"
            git push origin feature/mi-rama

        
      - name: Crear Pull Request
        run: |
              curl -X POST \
                -H "Authorization: Bearer ${{ secrets.MY_TOKEN}}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/pulls \
                -d '{
                  "title": "Actualización de opciones de componentes en Deploy.yml",
                  "head": "feature/change-inputs-components",
                  "base": "develop",
                  "body": "Este Pull Request actualiza las opciones de componentes en Deploy.yml."
                }'