name: Actualizar Componentes
run-name: Push hecho por parte de ${{ github.actor }}

on: 
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: write  
  pull-requests: write


jobs:
  actualizar-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Conseguir los nombres de los .json
        id: lista-json
        run: |
          all_archivos=$(find . -maxdepth 1 -type f -name "*.json" -exec basename {} .json \;)
          
          echo "archivos<<EOF" >> $GITHUB_OUTPUT
          echo "$all_archivos" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Actualizar los nuevos componentes
        run: |
          componentes="${{ steps.lista-json.outputs.archivos }}"
          options=$(echo "$componentes" | tr '\n' ' ' | sed 's/^/    - /')

          sed -i  "/component:/,/options:/ {
              /options:/ {
                n
                s|.*|$options|
              }
          }" .github/workflows/Deploy.yml

      - name: Configurar Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Crear y hacer push a la nueva rama
        run: |
          git checkout -b feature/change-inputs-components
          git add .github/workflows/Deploy.yml
          git commit -m "Actualización automática de opciones de componentes"
          git push origin feature/change-inputs-components


      - name: Autenticar GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Crear Pull Request
        run: |
          gh pr create \
            --title "Actualización de opciones de componentes en Deploy.yml" \
            --body "Este Pull Request actualiza las opciones de componentes en Deploy.yml." \
            --base develop \
            --head feature/change-inputs-components
