name: Actualizar Componentes
run-name: Push hecho por parte de ${{ github.actor }}

on: 
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  actualizar-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.ID_GIT_APP }}
          private_key: ${{ secrets.GIT_APP_TOKEN }}  

      - name: Clonar repositorio
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
      
      - name: Conseguir los nombres de los .json
        id: lista-json
        run: |
          all_archivos=$(find . -type f -name "*.json" | sed 's/\.json$//')

           echo "archivos<<EOF" >> $GITHUB_OUTPUT
           echo "$all_archivos" >> $GITHUB_OUTPUT
           echo "EOF" >> $GITHUB_OUTPUT

      - name: Actualizar los nuevos componentes
        run: |
             componentes="${{ steps.lista-json.outputs.archivos }}"
             options=$(echo "$componentes" | sed 's/^/                          - /')
         
             echo "Componentes a insertar: $options"
         
             awk -v new_options="$options" '
             /component:/ { print; in_block=1; next }

             /options:/ && in_block {
               print
               print new_options
               skip=1
               next
             }

             in_block && skip {
               if (/^[[:space:]]*-/) next
               else { in_block=0; skip=0 }
             }

             { print }
             ' .github/workflows/Deploy.yml > temp && mv temp .github/workflows/Deploy.yml
         

             cat .github/workflows/Deploy.yml

      - name: Crear Pull Request en el repositorio oficial usando create-pull-request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          title: "Actualización de opciones de componentes en Deploy.yml"
          body: "Este Pull Request actualiza las opciones de componentes en Deploy.yml."
          base: "develop"
          commit-message: "Actualización automática de opciones de componentes"
          branch: "feature/change-inputs-components"
